server:
  port: 8001

geli:
  weather:
    endpoints: ${WEATHER_ENDPOINT}
    moduleid: cooptimizer2

spring:
  rabbitmq:
    host: ${RABBIT_ENDPOINT}
    port: 5672
    username: guest
    password: guest

amqp:
  exchange: weather-service.exchange
  routingkey:
    pub:
      current: request.current_weatherdata
      forecasted: request.forecasted_weatherdata
    sub:
      current: cge.*.cooptimizer2.current
      forecasted: cge.*.cooptimizer2.forecasted