apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: weatherserivce
    variant: dev
  name: web-client-config
  namespace: kube-is-test
data:
  RABBIT_ENDPOINT: rabbitmq-svc
  RABBIT_PORT: "5672"
  WEATHER_ENDPOINT: http://weather-web-svc:5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatherserivce
    variant: dev
  name: web-client
  namespace: kube-is-test
spec:
  ports:
    - port: 80
      targetPort: 8001
  selector:
    app: weatherserivce
    variant: dev
    name: web-client
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weatherserivce
    variant: dev
  name: web-client
  namespace: kube-is-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherserivce
      variant: dev
  template:
    metadata:
      labels:
        app: weatherserivce
        name: web-client
        variant: dev
    spec:
      containers:
      - env:
        - name: RABBIT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: RABBIT_ENDPOINT
              name: web-client-config
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              key: RABBIT_PORT
              name: web-client-config
        - name: WEATHER_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: WEATHER_ENDPOINT
              name: web-client-config
        image: ininin3/rest-amqp-client:1.0
        imagePullPolicy: Always
        name: web-client-container
        ports:
        - containerPort: 8001
